palette="catppuccin_mocha"

format = """
[░▒▓](#a3aed2)\
[](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch$git_status\
[](fg:#394260 bg:#212736)\
$nodejs$rust$golang$php$python\
[](fg:#212736 bg:#1d2230)\
$time$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙 "
"Descargas" = "󱑤 "
"Música" = "󰎄 "
"Imágenes" = "  "
"Vídeos" = " "
"bin" = " "

[git_branch]
symbol = "  "
style = "bg:#394260"
format = '[[$symbol](fg:white bg:#394260) [$branch](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
conflicted = '[ =(fg:red bg:#394260)]'
ahead = '[  ${count}](yellow bg:#394260)'
behind = '[  ${count}](yellow bg:#394260)'
diverged = '[ ⇕  ${ahead_count}  ${behind_count}](yellow bg:#394260)'
up_to_date = '[ ✓ ](green bg:#394260)'
untracked = '[   ${count}](red bg:#394260)'
stashed = '  ${count}(yellow bg:#394260)'
modified = '[   ${count}](red bg:#394260)'
staged = '[ ++(${count}) ](green bg:#394260)'
renamed = '[ 󰸣 ${count}](yellow bg:#394260)'
deleted = '[  ${count}](yellow bg:#394260)'
format = '[[($all_status$ahead_behind )](bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[php]
symbol = ""
style = "bg:#212736"
format = '[ $symbol ($version) ](fg:#769ff0 bg:#212736)'

[python]
symbol = '󰌠'
style = "bg:#212736"
pyenv_version_name = false
format = '[ $symbol ($version) ($virtualenv) ](fg:#769ff0 bg:#1d2230)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[   $time ](fg:#a0a9cb bg:#1d2230)'

[cmd_duration]
min_time = 1000
format = "[  $duration ](fg:#a0a9cb bg:#1d2230)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

