[[mgr.prepend_keymap]]
on  = "!"
run = 'shell --block -- "$SHELL"'
desc = "Shell aquí"

[[mgr.prepend_keymap]]
on  = "<Enter>"
run = "plugin smart-enter"
desc = "Entrar si es dir, abrir si es archivo"

[[mgr.prepend_keymap]]
on  = "p"
run = "plugin smart-paste"
desc = "Pegar aquí"

[[mgr.prepend_keymap]]
on  = "f"
run = "plugin smart-filter"
desc = "Filtrar"

[[mgr.prepend_keymap]]
on  = "T"
run = "plugin toggle-pane min-preview"
desc = "Mostrar/ocultar preview"

[[mgr.prepend_keymap]]
on  = "<C-t>"
run = "plugin toggle-pane max-preview"
desc = "Maximizar/restaurar preview"

# Git sin romper prefijos g...
[[mgr.prepend_keymap]]
on  = [ "g", "s" ]
run = "plugin git"
desc = "Git status linemode"

[[mgr.prepend_keymap]]
on  = "+"
run = "plugin zoom in"
desc = "Zoom in preview"

[[mgr.prepend_keymap]]
on  = "-"
run = "plugin zoom out"
desc = "Zoom out preview"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]
desc = "Copiar URIs y yank"

[[mgr.prepend_keymap]]
on  = "R"
run = "plugin recycle-bin"
desc = "Reciclar / vaciar / restaurar"

[[mgr.prepend_keymap]]
on  = "<S-r>"
run = "plugin restore"
desc = "Restaurar último borrado"

[[mgr.prepend_keymap]]
on  = [ "g", "w" ]
run = "cd ~/Workspace"
desc = "Workspace"

[[mgr.prepend_keymap]]
on  = [ "g", "d" ]
run = "cd ~/Downloads"
desc = "Downloads"

[[mgr.prepend_keymap]]
on  = "."
run = "hidden toggle"
desc = "Toggle ocultos"

[[mgr.prepend_keymap]]
on = ["c","v"]
run = 'open --with tmux_here'
desc = "nvim en pane actual"

[[mgr.prepend_keymap]]
on = ["c","n"]
run = 'open --with tmux_win'
desc = "nvim en nueva ventana"

[[mgr.prepend_keymap]]
on = ["s","v"]
run = 'open --with tmux_vsplit'

[[mgr.prepend_keymap]]
on = ["s","s"]
run = 'open --with tmux_hsplit'
